### ISSUE TITLE
Support Pydantic Model parameters with postponed evaulation

### ISSUE THREAD

**Issue by chrisgoddard** [zby/LLMEasyTools#4]
Hi there!

Currently, if I decorate a function like:
```python

class Query(BaseModel):
    query: str
    region: str


def search(query: Query):
    ...

schema = get_tool_defs([search])
```

It works.

However, if have `from __future__ import annotations`, I get the error 
```bash
PydanticUserError: `search_ParameterModel` is not fully defined; you should define `Query`, then call `search_ParameterModel.model_rebuild()`.

```

Not sure how easy this would be to allow for but interested in your thoughts.

**Comment by zby** [comment]
Welcome my first contributor!

I am on vacations right now - but what version of python do you use? In 3.10 this from __future__ should not be needed.

I need to test this. I think I can add a special case for functions that have just one pydantic parameter - then I would not generate the class on the fly. Historically in the first versions of LLMEasyTools I did not do that dynamic generation and only used it for functions with single pydantic parameter.

**Comment by zby** [comment]
I've added your code to the test cases in: https://github.com/zby/LLMEasyTools/commit/e40df488d0ccd3dc517d3cb9310922d61fc0e297

When I add that import from future - it fails together with a lot of other tests. I'll need to debug it.

This is strange - because I work on python 3.10 and it should have postponed evaluations by default.

**Comment by zby** [comment]
I think I fixed this in https://github.com/zby/LLMEasyTools/commit/a0079970ccbf0e0b71cc8d2345aeac024279c16c - unfortunately it will not work with classes declared in nested blocks, only for global classes.

Please test it with your code.
